-- vim.o.backspace = { 'indent', 'eol', 'start' }
vim.o.shiftwidth = 4
vim.o.softtabstop = 4
vim.o.tabstop = 4
vim.o.expandtab = true
vim.o.cursorline = true
vim.o.clipboard = 'unnamedplus'
vim.o.incsearch = true
vim.o.ignorecase = true
vim.o.hlsearch = true
vim.o.backup = false
vim.o.writebackup = false
vim.o.swapfile = false
